export const HEADERS = [
  { key: "id", label: "ID" },
  { key: "title", label: "Title" },
  { key: "description", label: "Description" },
  { key: "neighborhood", label: "Neighborhood" },
  { key: "street", label: "Street" },
  { key: "reference", label: "Reference" },
  { key: "status", label: "Status" },
  { key: "image", label: "Image" },
  { key: "userId", label: "User ID" },
  { key: "createdAt", label: "Created At" },
  { key: "updatedAt", label: "Updated At" },
];

export const MOCKED_DATA = [
  {
    id: 1,
    title: "Vazamento de água na rua principal",
    description:
      "Há um vazamento de água na calçada em frente ao supermercado.",
    neighborhood: "Centro",
    street: "Rua Principal",
    reference: "Em frente ao estacionamento da praça",
    status: "Finalizado",
    image: "https://picsum.photos/400",
    userId: 1,
    createdAt: "2024-04-29T18:32:59.628Z",
    updatedAt: "2024-04-29T18:32:59.628Z",
  },
  {
    id: 2,
    title: "Lâmpada queimada no parque",
    description:
      "Uma das lâmpadas do poste no parque está queimada, deixando a área escura à noite.",
    neighborhood: "Vila Nova",
    street: "Rua das Flores",
    reference: "Próximo à esquina",
    status: "Aberto",
    image: "https://picsum.photos/400",
    userId: 2,
    createdAt: "2024-04-29T18:32:59.628Z",
    updatedAt: "2024-04-29T18:32:59.628Z",
  },
  {
    id: 3,
    title: "Bueiro entupido na esquina",
    description:
      "O bueiro na esquina da Rua das Flores está entupido e causando alagamentos.",
    neighborhood: "Jardim América",
    street: "Avenida Central",
    reference: "",
    status: "Andamento",
    image: "https://picsum.photos/400",
    userId: 1,
    createdAt: "2024-04-29T18:32:59.628Z",
    updatedAt: "2024-04-29T18:32:59.628Z",
  },
  {
    id: 4,
    title: "Passeio com buracos na Avenida Central",
    description:
      "Os buracos no passeio estão representando um perigo para os pedestres.",
    neighborhood: "Jardim Botânico",
    street: "Rua das Árvores",
    reference: "Próximo à escola",
    status: "Aberto",
    image: "https://picsum.photos/400",
    userId: 3,
    createdAt: "2024-04-29T18:32:59.628Z",
    updatedAt: "2024-04-29T18:32:59.628Z",
  },
  {
    id: 5,
    title: "Falta de coleta de lixo na Vila dos Pássaros",
    description:
      "O caminhão de lixo não passa pela Vila dos Pássaros há uma semana.",
    neighborhood: "Parque Industrial",
    street: "Rua dos Industriais",
    reference: "",
    status: "Andamento",
    image: "https://picsum.photos/400",
    userId: 2,
    createdAt: "2024-04-29T18:32:59.628Z",
    updatedAt: "2024-04-29T18:32:59.628Z",
  },
];